[package]
name = "star_trader"
version = "0.1.0"
authors = ["Roy Larson <roy.larson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.7.3"
